import { Product, Ethnicity, Category } from './types';

export const ETHNICITIES: Ethnicity[] = [
  'Gujarati', 'Marathi', 'Punjabi', 'Rajasthani', 'South Indian', 'Bengali', 'Kashmiri'
];

export const ETHNICITY_IMAGES: Record<Ethnicity, string> = {
  'Gujarati': 'https://vardhmanvacations.com/gujarat-tourism/img/people.jpg',
  'Marathi': 'https://media.istockphoto.com/id/1409714837/photo/young-indian-female-wearing-traditional-maharashtrian-red-saree-with-festive-look.jpg?s=612x612&w=0&k=20&c=keZ7Pd4J6PbnowxQI658nO5nxCoFhHSTTeXRO-Tsi3c=',
  'Punjabi': 'https://png.pngtree.com/thumb_back/fh260/background/20230609/pngtree-many-women-with-drums-in-bright-outfits-and-saris-walk-down-image_2932746.jpg',
  'Rajasthani': 'https://storage.needpix.com/rsynced_images/kalbeliya-4088757_1280.jpg',
  'South Indian': 'https://media.istockphoto.com/id/1212897504/photo/south-indian-young-family-with-classic-look-stock-photo.jpg?s=612x612&w=0&k=20&c=9vhm1Z8qWkSslaaHc5QNBZadOAvxhX7vZkbzqxWFl30=',
  'Kashmiri': 'https://www.travelertrails.com/wp-content/uploads/2022/11/Kashmiri-Dresses-1.jpg',
  'Bengali': 'https://www.azafashions.com/blog/wp-content/uploads/2025/12/featured5.jpg'
};

export const CATEGORIES: Category[] = ['Ethnic Wear', 'Jewellery'];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Royal Banarasi Silk Saree',
    description: 'Exquisite hand-woven Banarasi silk saree with intricate zari work, perfect for weddings and royal occasions.',
    price: 15000,
    rentPrice: 2500,
    category: 'Ethnic Wear',
    gender: 'Women',
    ageGroup: 'Adults',
    ethnicity: 'Bengali',
    images: ['https://medias.utsavfashion.com/media/catalog/product/cache/1/image/1000x/040ec09b1e35df139433887a97daa66f/p/u/pure-banarasi-georgette-silk-handloom-saree-in-royal-blue-v1-swz1216.jpg'],
    vendorName: 'Kashi Weaves',
    rating: 4.8,
    reviewsCount: 124,
    stock: 5,
    isAvailableForRent: true,
    createdAt: '2024-01-01',
  },
  {
    id: '2',
    name: 'Antique Gold Kundan Necklace',
    description: 'Traditional Rajasthani Kundan necklace set with semi-precious stones and gold plating.',
    price: 8500,
    rentPrice: 1200,
    category: 'Jewellery',
    gender: 'Women',
    ageGroup: 'Adults',
    ethnicity: 'Rajasthani',
    images: ['https://i.etsystatic.com/6868191/r/il/9090a9/1157983973/il_794xN.1157983973_sk7f.jpg'],
    vendorName: 'Jaipur Jewels',
    rating: 4.9,
    reviewsCount: 89,
    stock: 3,
    isAvailableForRent: true,
    createdAt: '2024-01-02',
  },
  {
    id: '3',
    name: 'Embroidered Sherwani for Men',
    description: 'Elegant ivory sherwani with detailed embroidery and royal buttons, ideal for grooms.',
    price: 22000,
    rentPrice: 4500,
    category: 'Ethnic Wear',
    gender: 'Men',
    ageGroup: 'Adults',
    ethnicity: 'Punjabi',
    images: ['https://content.jdmagicbox.com/quickquotes/images_main/plain-cotton-embroidered-ethnic-sherwani-for-groom-802686438-44nunfvm.jpg?impolicy=queryparam&im=Resize=(360,360),aspect=fit'],
    vendorName: 'Ludhiana Attire',
    rating: 4.7,
    reviewsCount: 56,
    stock: 2,
    isAvailableForRent: true,
    createdAt: '2024-01-03',
  },
  {
    id: '4',
    name: 'Kanchipuram Pattu Saree',
    description: 'Authentic South Indian Kanchipuram silk saree with traditional temple borders.',
    price: 18000,
    rentPrice: 3000,
    category: 'Ethnic Wear',
    gender: 'Women',
    ageGroup: 'Adults',
    ethnicity: 'South Indian',
    images: ['https://sunasa.in/cdn/shop/products/IMG_20221104_013654_1500x.jpg?v=1697397615'],
    vendorName: 'Chennai Silk House',
    rating: 4.9,
    reviewsCount: 210,
    stock: 8,
    isAvailableForRent: true,
    createdAt: '2024-01-04',
  },
  {
    id: '5',
    name: 'Bandhani Print Lehenga',
    description: 'Vibrant Gujarati Bandhani lehenga choli with mirror work, perfect for Navratri.',
    price: 12000,
    rentPrice: 1800,
    category: 'Ethnic Wear',
    gender: 'Women',
    ageGroup: 'Adults',
    ethnicity: 'Gujarati',
    images: ['https://www.sareez.com/uploads/sareez/products/red-georgette-bandhani-print-reception-wedding-heavy-border-lehenga-choli-141700774488558_m.jpg?v=523'],
    vendorName: 'Surat Ethnic Hub',
    rating: 4.6,
    reviewsCount: 78,
    stock: 12,
    isAvailableForRent: true,
    createdAt: '2024-01-05',
  },
  {
    id: '6',
    name: 'Temple Jewellery Jhumkas',
    description: 'Classic South Indian temple jewellery jhumkas with goddess motifs.',
    price: 3500,
    rentPrice: 500,
    category: 'Jewellery',
    gender: 'Women',
    ageGroup: 'Adults',
    ethnicity: 'South Indian',
    images: ['https://i.pinimg.com/originals/9c/79/76/9c79768a805d5db2111d1951b5a85ca9.jpg'],
    vendorName: 'Madurai Arts',
    rating: 4.8,
    reviewsCount: 45,
    stock: 15,
    isAvailableForRent: true,
    createdAt: '2024-01-06',
  },
  {
    id: '7',
    name: 'Kids Silk Pattu Pavadai',
    description: 'Traditional South Indian silk pavadai set for young girls, vibrant and comfortable.',
    price: 4500,
    rentPrice: 800,
    category: 'Ethnic Wear',
    gender: 'Kids',
    ageGroup: 'Kids',
    ethnicity: 'South Indian',
    images: ['https://www.spiceandcraft.com/cdn/shop/files/il_fullxfull.3778747487_t0th_acfcd015-6fab-4d15-8135-7c313714c82f.jpg?v=1721458336'],
    vendorName: 'Chennai Silk House',
    rating: 4.7,
    reviewsCount: 32,
    stock: 10,
    isAvailableForRent: true,
    createdAt: '2024-01-07',
  },
  {
    id: '8',
    name: 'Kids Dhoti Kurta Set',
    description: 'Elegant cotton dhoti kurta set for boys, perfect for festivals and ceremonies.',
    price: 3200,
    rentPrice: 600,
    category: 'Ethnic Wear',
    gender: 'Kids',
    ageGroup: 'Kids',
    ethnicity: 'Marathi',
    images: ['http://ramrajcotton.in/cdn/shop/files/5_50bbbf23-2217-46b2-92c7-27c8ee2febd4.jpg?v=1696584226'],
    vendorName: 'Pune Ethnic Store',
    rating: 4.5,
    reviewsCount: 28,
    stock: 15,
    isAvailableForRent: true,
    createdAt: '2024-01-08',
  }
];
